"""
FILE: backend/main.py  [MODIFIED]
RESPONSIBILITY: Application entry point — wires together all routes, middleware,
                and startup hooks.

TEAMMATE INTEGRATION:
  - Frontend (Vite, port 5173): CORS middleware below allows the React app to
    call this API from the browser without "blocked by CORS" errors.
  - Database: calls create_tables() on startup so SQLite is ready before the
    first request arrives.
  - All route files in backend/routes/ are registered here.

HOW TO START THE SERVER:
    From the repo root (NOT from inside backend/):
        uvicorn backend.main:app --reload --port 8000

    --reload  : auto-restarts when you save a .py file (development only)
    The database file (backend/treasury.db) is created automatically on first run.

INTERACTIVE DOCS (auto-generated by FastAPI):
    http://localhost:8000/docs   ← try every endpoint in the browser
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.models.database import create_tables
from backend.routes.invoice         import router as invoice_router
from backend.routes.bank_statement  import router as bank_statement_router
from backend.routes.reconciliation  import router as reconciliation_router
from backend.routes.results         import router as results_router


# ── App setup ─────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Global Treasury Agent API",
    description="AI-assisted cross-border payment reconciliation for SMEs.",
    version="1.0.0",
)

# CORS (Cross-Origin Resource Sharing):
# Browsers block JavaScript from calling APIs on a different port by default.
# This middleware tells the browser "it's OK for http://localhost:5173 (the
# React dev server) to talk to this API."  Without this, every fetch() in
# the frontend would fail with a CORS error.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite dev server (npm run dev)
        "http://localhost:5174",   # Vite fallback port (when 5173 is taken)
        "http://localhost:3000",   # alternative dev port
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5174",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Database init ─────────────────────────────────────────────────────────────

@app.on_event("startup")
def on_startup():
    """Run once when the server starts.  Creates all DB tables if they don't
    exist yet — safe to call even if the database already has data."""
    create_tables()


# ── Route registration ────────────────────────────────────────────────────────
# Each router handles a related group of endpoints.
# The 'tags' label groups them in the /docs UI.

app.include_router(invoice_router,        tags=["Invoice"])         # /upload-invoice, /invoices
app.include_router(bank_statement_router, tags=["Bank Statement"])  # /upload-bank-statement, /bank-transactions
app.include_router(reconciliation_router, tags=["Reconciliation"])  # /reconcile
app.include_router(results_router,        tags=["Results"])         # /results


# ── Health check ──────────────────────────────────────────────────────────────
# Simple endpoints the frontend (or a monitoring tool) can ping to verify the
# server is alive.  Dashboard.jsx uses the /health response indirectly by
# falling back to mock data when the backend is unreachable.

@app.get("/", tags=["Health"])
def root():
    return {"status": "ok", "service": "Global Treasury Agent API"}


@app.get("/health", tags=["Health"])
def health():
    return {"status": "healthy"}
